### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bduncan** [pjps/ndjbdns#24]
Hi,

I am experiencing an infrequent crash using the RHEL6 ndjbdns-1.06-1.el6.x86_64. The crash happens without apparent cause approximately every fortnight. I have finally managed to obtain a backtrace running under gdb. The kernel logs, the end of the -d3 logs and the stacktrace are below. Any advice welcome!

# dmesg:
dnscache[4192]: segfault at 12a ip 000000000040c259 sp 00007ffed858c180 error 6 in dnscache[400000+14000]
dnscache[11224]: segfault at 12a ip 000000000040c259 sp 00007ffdd927c810 error 6 in dnscache[400000+14000]
dnscache[18375]: segfault at 129 ip 000000000040c259 sp 00007ffe82d2a3a0 error 6 in dnscache[400000+14000]
dnscache[14364]: segfault at 12a ip 000000000040c259 sp 00007ffd63f29890 error 6 in dnscache[400000+14000]

# dnscache logs:
```
Nov 26 2015 22:06:52 Q1520171 129.215.102.37:60201 35835 A? outlook.office365.com.
     cc ns office365.com. ns3.msft.net.
     cc ns office365.com. ns1.msft.net.
     cc ns office365.com. ns2.msft.net.
     cc ns office365.com. ns4.msft.net.
     cc ns office365.com. ns1a.o365filtering.com.
     cc ns office365.com. ns2a.o365filtering.com.
     cc ns office365.com. ns4a.o365filtering.com.
     cc A ns3.msft.net.
     cc A ns1.msft.net.
     cc A ns2.msft.net.
     cc A ns4.msft.net.
     cc A ns1a.o365filtering.com.
     cc A ns2a.o365filtering.com.
     cc A ns4a.o365filtering.com.
 + tx 0 A outlook.office365.com. office365.com. 208.76.45.53 157.56.110.11 157.56.116.52 208.84.0.53 157.55.133.11 208.84.2.53 193.221.113.53
 + merge 208.76.45.53 A outlook.office365.com.
Nov 26 2015 22:06:52 drop Q1519875 timed out
Nov 26 2015 22:06:52 Q1520172 129.215.113.184:37960 685 A? imap.staffmail.ed.ac.uk.
     cc ns ed.ac.uk. dns2.dcs.ed.ac.uk.
     cc ns ed.ac.uk. dns.dcs.ed.ac.uk.
     cc ns ed.ac.uk. cancer.ucs.ed.ac.uk.
     cc ns ed.ac.uk. xlab-0.ed.ac.uk.
     cc ns ed.ac.uk. lewis.ucs.ed.ac.uk.
     cc ns ed.ac.uk. dns2.dcs.ed.ac.uk.
     cc ns ed.ac.uk. dns.dcs.ed.ac.uk.
     cc ns ed.ac.uk. cancer.ucs.ed.ac.uk.
     cc ns ed.ac.uk. xlab-0.ed.ac.uk.
     cc ns ed.ac.uk. lewis.ucs.ed.ac.uk.
 + tx 2 A dns2.dcs.ed.ac.uk. . 192.33.4.12 192.5.5.241 202.12.27.33 199.7.83.42 198.41.0.4 199.7.91.13 192.203.230.10 193.0.14.129 192.58.128.30 192.112.36.4 128.63.2.53 192.228.79.201 192.36.148.17
 + merge 192.33.4.12 A dns2.dcs.ed.ac.uk.
Nov 26 2015 22:06:52 drop Q1519876 timed out
Nov 26 2015 22:06:52 Q1520173 129.215.113.184:37960 51219 AAAA? imap.staffmail.ed.ac.uk.
     cc ns ed.ac.uk. dns2.dcs.ed.ac.uk.
     cc ns ed.ac.uk. dns.dcs.ed.ac.uk.
     cc ns ed.ac.uk. cancer.ucs.ed.ac.uk.
     cc ns ed.ac.uk. xlab-0.ed.ac.uk.
     cc ns ed.ac.uk. lewis.ucs.ed.ac.uk.
     cc ns ed.ac.uk. dns2.dcs.ed.ac.uk.
     cc ns ed.ac.uk. dns.dcs.ed.ac.uk.
     cc ns ed.ac.uk. cancer.ucs.ed.ac.uk.
     cc ns ed.ac.uk. xlab-0.ed.ac.uk.
     cc ns ed.ac.uk. lewis.ucs.ed.ac.uk.
 + tx 2 A dns2.dcs.ed.ac.uk. . 199.7.91.13 128.63.2.53 199.7.83.42 192.33.4.12 192.228.79.201 192.112.36.4 202.12.27.33 192.58.128.30 192.5.5.241 192.36.148.17 193.0.14.129 198.41.0.4 192.203.230.10
 + merge 199.7.91.13 A dns2.dcs.ed.ac.uk.
 + merge 129.215.160.240 33 _mssms_mp_ue3._tcp.ed.ac.uk.
 + merge 129.215.160.240 33 _mssms_mp_ue3._tcp.ed.ac.uk.
 + merge 129.215.166.13 33 _mssms_mp_ue3._tcp.ed.ac.uk.
Nov 26 2015 22:06:52 servfail _mssms_mp_ue3._tcp.ed.ac.uk. input/output error
Nov 26 2015 22:06:52 R1438088 2:server failure 0 45

Program received signal SIGPIPE, Broken pipe.
0x0000003eea6db520 in __write_nocancel () from /lib64/libc.so.6

(gdb) bt full
#0  0x0000003eea6db520 in __write_nocancel () from /lib64/libc.so.6
No symbol table info available.
#1  0x0000000000403490 in t_rw (j=1) at dnscache.c:337
        r = <value optimized out>
        ch = <value optimized out>
        q = 0x818ec0 "\r_mssms_mp_ue3\004_tcp\003see\002ed\002ac\002uk"
        toread = <value optimized out>
        qtype = "\206\202"
        qclass = "\230", <incomplete sequence \362>
        x = 0x6be6f0
#2  0x000000000040413c in doit (argc=<value optimized out>, argv=<value optimized out>) at dnscache.c:582
        stamp = {sec = {x = 4611686019875963526}, nano = 629262500, atto = 0}
        deadline = {sec = {x = 4611686019875963139}, nano = 618607500, atto = 0}
        iolen = <value optimized out>
        j = <value optimized out>
        r = <value optimized out>
#3  main (argc=<value optimized out>, argv=<value optimized out>) at dnscache.c:832
        i = <value optimized out>
        t = 1447843598
        sa = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {140737488348704, 270215943808, 270218173088, 140737488348720, 140737488348776, 270218172184, 140737488348800, 1910330751, 270215978762, 0, 
              140737488348800, 0, 0, 140733193388032, 270218172184, 0}}, sa_flags = 0, sa_restorer = 0x7ffff7fef700}
        cachesize = 5000000
        x = <value optimized out>
        char_seed = "<value redacted>"
(gdb) 
```

# /etc/ndjbdns/dnscache.conf:
```
CACHESIZE=5000000
DATALIMIT=8000000
IP=129.215.215.53
IPSEND=0.0.0.0
UID=2
GID=2
ROOT=/etc/ndjbdns
MERGEQUERIES=1
DEBUG_LEVEL=3
```

I'm confused, because looking at the code: 1) SIGPIPE should be ignored and, 2) The line given in the backtrace should never be reached because:

```
(gdb) print (struct tcpclient)*x
$3 = {q = {loop = 0, level = 0, name = {0x3a766e <Address 0x3a766e out of bounds>, 0xf8ed3002c1722 <Address 0xf8ed3002c1722 out of bounds>, 0x36be7c <Address 0x36be7c out of bounds>, 0x0, 0x17d79a <Address 0x17d79a out of bounds>}, 
    control = {0x278e7f00000000 <Address 0x278e7f00000000 out of bounds>, 0x0, 0x0, 0x0, 0x2393dd <Address 0x2393dd out of bounds>}, ns = {{0x0, 0x0, 0x0, 0x0, 0x3c303e003b3adb <Address 0x3c303e003b3adb out of bounds>, 0x0, 0x0, 0x0, 
        0x206fce00000000 <Address 0x206fce00000000 out of bounds>, 0x8fbfd003d2099 <Address 0x8fbfd003d2099 out of bounds>, 0x0, 0x1ac0fa <Address 0x1ac0fa out of bounds>, 0x17f4e4 <Address 0x17f4e4 out of bounds>, 0x0, 0x0, 0x0}, {0x0, 
        0x0, 0x433020 <Address 0x433020 out of bounds>, 0x0, 0x25f011 <Address 0x25f011 out of bounds>, 0x85a2d0006003b <Address 0x85a2d0006003b out of bounds>, 0x0, 0x38a984003c83af <Address 0x38a984003c83af out of bounds>, 
        0x36beac <Address 0x36beac out of bounds>, 0x2a715a <Address 0x2a715a out of bounds>, 0x3c34dc <Address 0x3c34dc out of bounds>, 0x30fcc5 <Address 0x30fcc5 out of bounds>, 
        0x3e799d00000000 <Address 0x3e799d00000000 out of bounds>, 0x0, 0x0, 0x0}, {0x3f76d300000000 <Address 0x3f76d300000000 out of bounds>, 0x0, 0x3414e1 <Address 0x3414e1 out of bounds>, 
        0x3a11a600000000 <Address 0x3a11a600000000 out of bounds>, 0x202415 <Address 0x202415 out of bounds>, 0x343a87 <Address 0x343a87 out of bounds>, 0x0, 0x426c58 <Address 0x426c58 out of bounds>, 0x0, 
        0x827d7001daf0e <Address 0x827d7001daf0e out of bounds>, 0x314146 <Address 0x314146 out of bounds>, 0x256341 <Address 0x256341 out of bounds>, 0x37825b00199706 <Address 0x37825b00199706 out of bounds>, 0x0, 0x0, 0x0}, {0x0, 
        0x2bda98 <Address 0x2bda98 out of bounds>, 0x0, 0x42b1af <Address 0x42b1af out of bounds>, 0x107a0f <Address 0x107a0f out of bounds>, 0x0, 0x17b037 <Address 0x17b037 out of bounds>, 0x0, 0x0, 0x0, 0x0, 
        0x1adc3d002b3c1f <Address 0x1adc3d002b3c1f out of bounds>, 0x0, 0x0, 0x0, 0x0}, {0x0, 0xf50b600000000 <Address 0xf50b600000000 out of bounds>, 0x689960040225a <Address 0x689960040225a out of bounds>, 
        0xe2014 <Address 0xe2014 out of bounds>, 0x1c5caa <Address 0x1c5caa out of bounds>, 0x370fbf <Address 0x370fbf out of bounds>, 0x425ffb0029104d <Address 0x425ffb0029104d out of bounds>, 0x281d1d <Address 0x281d1d out of bounds>, 
        0x0, 0x0, 0x6000c00000000 <Address 0x6000c00000000 out of bounds>, 0xf1aed00000000 <Address 0xf1aed00000000 out of bounds>, 0x0, 0x3405d6 <Address 0x3405d6 out of bounds>, 0x69f8c00000000 <Address 0x69f8c00000000 out of bounds>, 
        0x42183b002ee319 <Address 0x42183b002ee319 out of bounds>}}, servers = {'\000' <repeats 16 times>, "\035T/", '\000' <repeats 17 times>"\212, E+", '\000' <repeats 13 times>"\326, \317\020\000\000\000\000\000\000\000\000", 
      "\000\000\000\000\000\000\000\000\373\n-", '\000' <repeats 17 times>"\246, \251$", '\000' <repeats 21 times>, "\006j\037\000\000\000\000\000\000\000\000", 
      '\000' <repeats 16 times>"\377, aB\000\000\000\000\000\006\021*", '\000' <repeats 21 times>, "\024\323$\000\000\000\000\000\221\000\070\000\000\000\000", 
      "15G\000\000\000\000\000\000\000\000\000\250\017\020", '\000' <repeats 29 times>, "j\260!\000\000\000\000\000\000\000\000\000f\370\017\000d\235-", 
      '\000' <repeats 20 times>, "\030A ", '\000' <repeats 21 times>, "rG\023", '\000' <repeats 16 times>}, alias = {0x0, 0x0, 0x10a19e <Address 0x10a19e out of bounds>, 0x0, 0x0, 0x3cf750 <Address 0x3cf750 out of bounds>, 0x0, 0x0, 0x0, 
      0x0, 0x35d576 <Address 0x35d576 out of bounds>, 0x0, 0x0, 0x21f30000000000 <Address 0x21f30000000000 out of bounds>, 0x0, 0x0}, aliasttl = {0, 0, 0, 2048518, 0, 0, 0, 0, 0, 0, 0, 2271439, 0, 0, 1311812, 0}, 
    localip = "\000\000\000", type = "\000", class = "\000", dt = {query = 0x1de033 <Address 0x1de033 out of bounds>, querylen = 0, packet = 0x0, packetlen = 0, s1 = 4652156, tcpstate = 2962291, udploop = 0, curserver = 2597278, 
      deadline = {sec = {x = 0}, nano = 10072866540224512, atto = 18511519500993177}, pos = 0, servers = 0x424e6a <Address 0x424e6a out of bounds>, localip = "\000\000\000", qtype = "\232\253", master = 0x2ff885, slaves = {0x0, 
        0x40a9d000000000, 0x0, 0x34d32000000000, 0x584f6, 0x0, 0x201e7800397473, 0x4195e700000000, 0x1dd4fd, 0x370a6200000000, 0x3141c6, 0x0, 0x0, 0x0, 0x201f6100000000, 0x3af392, 0x2d8c64, 0x3b418e00255b0d, 0x2acf0800000000, 0x2eb6a4, 
        0x3c72cf, 0x971f400392e69, 0x393a17, 0x0, 0x26a79700000000, 0x0, 0x1ab10500000000, 0x3b6886, 0x0, 0x16e8e6000a4e5f, 0x1ee0e8, 0x0, 0x0, 0x25a07800000000, 0x376e55, 0x33f476, 0x0, 0x2303f900000000, 0x0, 0x0, 0xe041c, 0x0, 
        0x2eebf300000000, 0x0, 0x1b3aa900000000, 0x225ec600207cb4, 0x0, 0x8412700422df1, 0x4707c8, 0x108c7e, 0x0, 0x0, 0x0, 0x20cf7900000000, 0x0, 0x126c63, 0xf5e0c00000000, 0x3f0120001adc0a, 0x0, 0x0, 0x1b9c5600000000, 0x4795e20042329a, 
        0x49e08600000000, 0x0, 0x33aae400000000, 0x0, 0x10563600000000, 0x0, 0x35592a, 0x256f6f00000000, 0x0, 0x435ec200000000, 0x47c2ec003dcb5c, 0x227d4500000000, 0x0, 0x3c0b8c00000000, 0x3094c9, 0x0, 0x0, 0x3e923d002c1c41, 0x0, 0x0, 
        0x0, 0x0, 0x0, 0x4c302300000000, 0x665ba, 0x0, 0x376e1500000000, 0x37f75900000000, 0x0, 0x0, 0x0, 0x0, 0x15b74e00000000, 0x0, 0x71c13, 0x0, 0x0, 0x0, 0x2977ad, 0x3cf45b00000000, 0x0, 0x33c0d3, 0x207c2a, 0x34f6e800000000, 0x0, 
        0x0, 0x0, 0x0, 0x0, 0x322b0e00000000, 0x367aa700000000, 0x644e00027ce99, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x457bb900360291, 0x0, 0x0, 0x0, 0x0, 0x35b50c00000000, 0x0, 0x0, 0x0, 0x0, 0x28376300000000, 0x0, 0x39c5d0001d32a4, 
        0x1ac76b00000000, 0x0, 0x31b38900000000, 0x3c79d9, 0x0, 0x86f0900000000, 0x0, 0x2a1c6600000000, 0x0, 0x0, 0x0, 0x0, 0x1952220025fc41, 0x389b3d00000000, 0x39a015, 0x416173, 0x0, 0x0, 0x26041000000000, 0x0, 0x0, 0x0, 
        0x2c0efb00000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2dacc200000000, 0x0, 0x3fcd1500000000, 0x0, 0x3771e2, 0x0, 0x55b0800000000, 0x0, 0x42136000000000, 0x0, 0x0, 0x0, 0x13f9ad, 0x235ede004246c0, 0x0, 0x3d233100000000, 0x0, 0x0, 0x22813a, 
        0x0, 0x0, 0x0, 0x331ed800000000, 0x0, 0x0, 0x40b3f400000000, 0x21705200000000, 0x0, 0x2b4990, 0x0, 0x227c31, 0xab16a00000000, 0x0, 0x41a45e00000000, 0x424a52, 0x1efa3c, 0x1b2c8d0037987e, 0x0, 0x0}, nslaves = 0}}, start = {sec = {
      x = 0}, nano = 0, atto = 3853814}, timeout = {sec = {x = 0}, nano = 2078172, atto = 0}, active = 5400835475374080, io = 0x0, ip = "V\343:", port = 40639, id = "\024", tcp = 0, state = 0, buf = 0x0, len = 0, pos = 2913186}
(gdb) print x->state
Attempt to extract a component of a value that is not a structure pointer.
(gdb) print ((struct tcpclient)*x).state
$4 = 0
```

Help!
Thanks :)
Bruce

**Comment by Tuuux** [comment]
Bye the past on 64bit system , the best pratice was to edit conf-ld and  -m64, i don't know if it's related and how n-djbdns deal with they option. I recommand you to follow instruction about compliter flag inside .INSTALL file.

You GDB trace look you are exceeds the bounds of a array, mais be you DATALIMIT is too small or you have a LD Link make on the worng way.

I hope it will help a bit

Regards
